# -*- coding: utf-8 -*-
"""Internship day-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TGAAhtgAZNvRnyEiJtR_fN2BJ56H8l9e

EXAMPLES FOR VARIABLES AND DATA TYPES
"""

name="Rithika"
age=19
OGPA=8.5
placed=False
print("Student Name:",name)
print("Age:",age)
print("OGPA:",OGPA)
print("Placed:",placed)
print(type(name))
print(type(age))
print(type(OGPA))
print(type(placed))

name="rithika"
print(len(name))